### ISSUE TITLE
Doesn't cope with private registry with no '.' in hostname

### ISSUE THREAD

**Issue by robbruce** [concourse/docker-image-resource#90]
If your private registry does not contain a '.', then due to the logic in the following code, the function assumes that you are not using a private registry and attempts to use docker hub.

https://github.com/concourse/docker-image-resource/blob/e6ffb336064e606b1d802a4ddc9cdab69553d0bd/assets/common.sh#L105

Scenarios like this can crop up when concourse and your registry are on the same network, say within a docker network.

I'm using nexus for my private docker registry/proxy, but if I use the docker FQDN when logging in I get an HTTP 400; yes this is a Nexus issue, but the assumption in the code above is still wrong.

**Comment by vito** [comment]
Would the resource be able to resolve that host? It'd need to be something configured in `/etc/hosts` which isn't configured or configurable in the container.

**Comment by robbruce** [comment]
Yes, if you setup garden dns server to be another container running dnsmasq and allow host access.

**Comment by laureled** [comment]
Facing the same issue.  Our Concourse DNS resolver has a search domain.  Using hostname:5000/name as the repository fails.  hostname should be a valid hostname.

**Comment by imranismail** [comment]
I am facing the same issue with google cloud registry.

```yaml
resources:
- name: github
  type: git
  source:
    uri: git@github.com:org/repo.git
    branch: master
    private_key: {{git_private_key}}
    paths: [Dockerfile]

- name: gcr
  type: docker-image
  source:
    respository: asia.gcr.io/project-id/image-name
    username: _json_key
    password: {{service_account_key}}
    email: does-not-matter@example.com

jobs:
- name: deploy
  plan:
  - get: github
    trigger: true
  - put: gcr
    params:
      build: gcr
```

**Comment by chendrix** [comment]
@robbruce is this solved by concourse/concourse#1145?

**Comment by maritz** [comment]
Facing the same issue.

I would like to use the docker service name of my registry as the domain, instead of the actual public-facing domain.

This way I could circumvent the proxy that sits in front of my docker registry.

**Comment by xtremerui** [comment]
Just check back if folks still facing this problem. Potentially we could port the change in `check` https://github.com/concourse/docker-image-resource/pull/100 to the in/out script to fix this issue.
